-- TABLES --
CREATE TABLE TICKET (
    ID INT,
    OWNERID INT,
    ASSIGNEDID INT,
    SERVICEID INT,
    TITLE VARCHAR(200),
    DESCRIPTION MEDIUMTEXT,
    SEVERITYID INT,
    STATUSID INT,
    CREATIONDATE DATETIME
);

CREATE TABLE USER (
    ID INT,
    NAME VARCHAR(60),
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(20),
    IMAGE BLOB
);

CREATE TABLE SUPPORTUSER (
    ID INT,
    USERID INT,
    ISADMIN CHAR(1)
);

CREATE TABLE SERVICE (
    ID INT,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200)
);

CREATE TABLE ATTACHMENT (
    ID INT,
    TICKETID INT,
    ARCHIVE BLOB
);

CREATE TABLE COMMENT (
    ID INT,
    TICKETID INT,
    OWNERID INT,
    CREATIONDATE DATETIME,
    COMMENTTEXT TEXT
);

-- PRIMARY KEYS --
ALTER TABLE TICKET ADD CONSTRAINT PK_TICKET PRIMARY KEY (ID);
ALTER TABLE USER ADD CONSTRAINT PK_USER PRIMARY KEY (ID);
ALTER TABLE SUPPORTUSER ADD CONSTRAINT PK_SUPPORTUSER PRIMARY KEY (ID);
ALTER TABLE SERVICE ADD CONSTRAINT PK_SERVICE PRIMARY KEY (ID);
ALTER TABLE ATTACHMENT ADD CONSTRAINT PK_ATTACHMENT PRIMARY KEY (ID);
ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (ID);

-- FOREIGN KEYS --
ALTER TABLE TICKET ADD CONSTRAINT FK_OWNER_ID FOREIGN KEY (OWNERID) REFERENCES USER;
ALTER TABLE TICKET ADD CONSTRAINT FK_ASSIGNED_ID FOREIGN KEY (ASSIGNEDID) REFERENCES SUPPORTUSER;
ALTER TABLE TICKET ADD CONSTRAINT FK_SERVICE_ID FOREIGN KEY (SERVICEID) REFERENCES SERVICE;
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_ATTACHMENT_ID FOREIGN KEY (TICKETID) REFERENCES TICKET;
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_ID FOREIGN KEY (TICKETID) REFERENCES TICKET;
