version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'unicamptickets'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
  backend:
    image: node:8.1
    volumes:
      - ../unicamp-tickets:/my-app
    ports:
      - 3000:3000
    command: bash -c "cd /my-app && npm i && npm i -g nodemon && nodemon app.js"  
  frontend:
    # gerar build e dps colocar para rodar 
    image: nginx:1.17
    volumes:
      - ../unicamp-tickets/dist:/usr/share/nginx/html
    ports:
      - 8080:80
    #command: bash -c "nginx -g deamon"s
